# make use of vm's
sudo: 'required'

# xenial is pretty old, but not as bad as trusty...
dist: xenial

#language: java

#jdk:
#  - oraclejdk8

# have the docker service set up (we'll
# update it later)
services:
  - docker

# adding additional apt packages
addons:
  apt:
    packages:
      - qemu-user-static
      # from the original main.sh
      - realpath
      - build-essential
      - python
      - python-pip
      - python-dev
      - openssl
      - libssl-dev
      - libevent-dev
      - git

jobs:
  include:
    - stage: install
      name: build amd64
      # prepare the machine before any code
      # installation scripts
      before_install:
        - './.travis/main.sh'
        - './.travis/setup_emulation.sh'

      #install:
      #  - python2 bootstrap.py
        # Installs testing toolkit
        #- python2 bootstrap.py --crate
      #  - python2 bootstrap.py --testing

      script:
        #- .travis/bootstrap_image.sh -u amd64 -r debian -t 10 -a amd64 -i laroque/volttron-docker:`echo ${TRAVIS_BRANCH} | tr / _` -p build
        - .travis/bootstrap_image.sh -u amd64 -r python -t 2.7-buster -a amd64 -i laroque/volttron-docker:`echo ${TRAVIS_BRANCH} | tr / _` -p build

      # only execute the following instructions in
      # the case of a success (failing at this point
      # won't mark the build as a failure).
      # To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
      # filled you need to either use `travis`' cli 
      # and then `travis set ..` or go to the travis
      # page of your repository and then change the 
      # environment in the settings pannel.
      after_success:
        #- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
        #    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
        #    ./.travis/build-docker.sh -p ;
        #  fi
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u amd64 -r python -t 2.7-buster -a amd64 -i laroque/volttron-docker:`echo ${TRAVIS_BRANCH} | tr / _` -p push
    - stage: install
      name: build arm7
      before_install:
        - './.travis/main.sh'
        - './.travis/setup_emulation.sh'
      script:
        - .travis/bootstrap_image.sh -u arm32v7 -r python -t 2.7-buster -a arm7 -i laroque/volttron-docker:`echo ${TRAVIS_BRANCH} | tr / _` -p build
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/bootstrap_image.sh -u arm32v7 -r python -t 2.7-buster -a arm7 -i laroque/volttron-docker:`echo ${TRAVIS_BRANCH} | tr / _` -p push
    - stage: manifest
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - .travis/build_manifest.sh -a arm -a amd64 -n laroque/volttron-docker:`echo ${TRAVIS_BRANCH} | tr / _`
