# make use of vm's
sudo: 'required'

# xenial is pretty old, but not as bad as trusty...
dist: xenial

#language: java

#jdk:
#  - oraclejdk8

# have the docker service set up (we'll
# update it later)
services:
  - docker

# adding additional apt packages, required
# for multi-architecture builds
addons:
  apt:
    packages:
      - qemu-user-static

# prepare the machine before any code
# installation scripts
before_install:
  - './.travis/main.sh'
  - './.travis/setup_emulation.sh'

#install:
#  - python2 bootstrap.py
  # Installs testing toolkit
  #- python2 bootstrap.py --crate
#  - python2 bootstrap.py --testing

script:
  #- 'ci-integration/run-tests.sh'
  - './.travis/build-docker.sh -b'

# only execute the following instructions in
# the case of a success (failing at this point
# won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# filled you need to either use `travis`' cli 
# and then `travis set ..` or go to the travis
# page of your repository and then change the 
# environment in the settings pannel.
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      ./.travis/build-docker.sh -p ;
    fi

