version: '3'
services:
  volttron:
    hostname: vc
    image: bonicim/volttron-docker-dev:test
    ports:
      - 8080:8080
      #- 23916:22916
      #- 8443:8443
      #- 6671:5671    # ampqs port
      #- 25671:15671  # management port
    volumes:
      - ./platform_config.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000