version: '3'
services:
  volttron1:
    container_name: volttron1
    hostname: volttron1
    build:
      context: .
      args:
        install_rmq: 'false'
    image: eclipsevolttron/volttron:v-docker-latest
    ports:
      # host_port:container_port
      # http port for volttron central
      - 8443:8443
    volumes:
      - ./platform_config.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
