version: '3'
services:
  volttron1:
    container_name: volttron1
    hostname: volttron1
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        install_rmq: 'false'
    image: volttron/volttron-docker-dev-zmq
    ports:
      # host_port:container_port
      # http port for volttron central
      - 8080:8080
    volumes:
      - ./platform_config.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
      - ./core:/startup

    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
